#! /bin/bash

node testArrayDiff.js                   
node testMappingLengths.js
node testArrayIntersection.js           
node testNumbersAboveThreshold.js
node testArrayUnion.js                  
node testNumbersBeloweThreshold.js
node testAscendingOrder.js              
node testOddSeries.js
node testCountingEvenNumbers.js         
node testPartitionArray.js
node testCountingOddNumbers.js          
node testReverse.js
node testDescendingOrder.js             
node testReverseFibonnaci.js
node testEvenSeries.js                  
node testRotateArray.js
node testExtractDigits.js               
node testSelectingEverySecondElement.js
node testFindAverage.js                 
node testSmallestNumber.js
node testGreatestNumber.js              
node testSumOfAListOfNumbers.js
node testIndexOfANumber.js              
node testUniqueArrayElements.js
node testIsSubset.js                    
node testZipArray.js
